# Generated by `ii init fish`. Put `ii init fish | source` in config.fish.
function ii --description 'Two taps. Any directory.'
    if test (count $argv) -gt 0; and test "$argv[1]" = init
        command ii $argv
        return $status
    end
    for _ii_arg in $argv
        switch $_ii_arg
            case --
                break
            case -h --help -V --version --print0
                command ii $argv
                return $status
        end
    end
    # split0 preserves embedded and trailing newlines. The final field is status.
    set -l _ii_result (begin
        command ii --print0 $argv
        printf '%s\0' $status
    end | string split0)
    set -l _ii_status $_ii_result[-1]
    if test "$_ii_status" -eq 130
        return 0
    end
    if test "$_ii_status" -ne 0
        return $_ii_status
    end
    if test (count $_ii_result) -ne 2
        return 1
    end
    builtin cd -- "$_ii_result[1]"
end
