# Generated by `ii init powershell`. Intended for PowerShell 7 on Windows.
function global:ii {
    $binary = (Get-Command ii -CommandType Application -ErrorAction Stop).Source
    foreach ($argument in $args) {
        if ($argument -eq '--') { break }
        if ($argument -in @('init', '-h', '--help', '-V', '--version', '--print0')) {
            & $binary @args
            return
        }
    }
    $target = & $binary @args
    $result = $LASTEXITCODE
    if ($result -eq 130) { $global:LASTEXITCODE = 0; return }
    if ($result -ne 0) { return }
    if ($null -ne $target -and "$target".Length -gt 0) {
        # LiteralPath is essential: brackets and wildcard characters are filenames.
        Set-Location -LiteralPath $target -ErrorAction Stop
    }
}
