# Generated by `ii.exe init powershell`. Intended for PowerShell 7 on Windows.
# PowerShell ships an `ii` alias for Invoke-Item. Remove the alias so it cannot
# take precedence over the navigator function. Invoke-Item remains available.
Remove-Alias -Name ii -Scope Local -Force -ErrorAction SilentlyContinue
Remove-Alias -Name ii -Scope Global -Force -ErrorAction SilentlyContinue

function global:ii {
    $binary = (Get-Command ii.exe -CommandType Application -ErrorAction Stop).Source
    if ($args.Count -gt 0 -and $args[0] -eq 'init') {
        & $binary @args
        return
    }
    foreach ($argument in $args) {
        if ($argument -eq '--') { break }
        if ($argument -in @('-h', '--help', '-V', '--version', '--print0')) {
            & $binary @args
            return
        }
    }
    $target = & $binary @args
    $result = $LASTEXITCODE
    if ($result -eq 130) { $global:LASTEXITCODE = 0; return }
    if ($result -ne 0) { return }
    if ($null -ne $target -and "$target".Length -gt 0) {
        # LiteralPath is essential: brackets and wildcard characters are filenames.
        Set-Location -LiteralPath $target -ErrorAction Stop
    }
}
