# Generated by `ii init bash` / `ii init zsh`. Evaluate once in your shell profile.
ii() {
    local _ii_arg _ii_result _ii_status
    # Informational/protocol commands must not have their output interpreted as a path.
    for _ii_arg in "$@"; do
        case "$_ii_arg" in
            --) break ;;
            init|-h|--help|-V|--version|--print0)
                command ii "$@"
                return $?
                ;;
        esac
    done
    # A sentinel preserves even trailing newlines in a Unix directory name.
    # The if-condition also makes cancellation safe under `set -e`.
    if _ii_result="$(command ii "$@"; _ii_status=$?; printf '.'; exit "$_ii_status")"; then
        _ii_result=${_ii_result%.}
        [ -n "$_ii_result" ] || return 0
        builtin cd -- "$_ii_result"
    else
        _ii_status=$?
        [ "$_ii_status" -eq 130 ] && return 0
        return "$_ii_status"
    fi
}
